#!/bin/sh
#
# Telegram notifier.
#

echo "*********************************"
echo "Telegram token: ${TELEGRAM_TOKEN}"
echo "Telegram user: ${TELEGRAM_NOTIFY}"
echo "*********************************"


telegram-bridge -redis-host=redis:6379 \
                -token=${TELEGRAM_TOKEN} \
                -recipient=${TELEGRAM_NOTIFY}
