#!/bin/sh
#
# Loop constantly adding the tests to the file
#


#
# Loop forever
#
while true; do

    #
    # Add all tests
    #
    for file in /etc/overseer/*.cfg; do

        #
        # Redis comes from "redis"
        #
        echo "Adding tests from ${file}"
        overseer enqueue -redis-host=redis:6379 $file
    done

    #
    # Repeat in a minute
    #
    sleep 59

done
